/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.addControl;
import Controller.deleteControl;
import Controller.updateController;
import Model.DBConnection;
import static Model.DBConnection.getConnection;
import Model.tableLoad;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tharapathi
 */
public class StudentView extends javax.swing.JFrame {

    /**
     * Creates new form StudentView
     */
    public StudentView() {
        initComponents();
        loadTableData();
        
        
        
        
        
        
    }
    Connection conn;
    PreparedStatement pst;
   // public void tableLoad(){
   
           // try {
               
                //Class.forName("com.mysql.cj.jdbc.Driver");
               
                // Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagementsystem?useSSL=false","root","");
                //Statement stmt = DBConnection.getStatementConnection();
         
                //ResultSet rs = stmt.executeQuery("SELECT * FROM student ");
               
            //DefaultTableModel tb1Model = (DefaultTableModel)sTB.getModel();
            //tb1Model.setRowCount(0);
           
            //while(rs.next()){
                //String Id= rs.getString("id");
                //String name= rs.getString("name");
                //String address= rs.getString("address");
                //String birthday= rs.getString("birthday");
                //String gender= rs.getString("gender");
               
                //String sTB[]= {Id, name, address, birthday, gender};
                //tb1Model.addRow(sTB);
               
            //}
           
        //} catch (Exception e) {
       // }
    //}
    public void search(){
        String srch = searchFLD.getText();
        tableLoad tableLoader = new tableLoad();
        ResultSet resultSet = tableLoader.searchData(srch);
        tableSearch(resultSet);
    }
    
    public void tableSearch(ResultSet result) {
        sTB.setModel(DbUtils.resultSetToTableModel(result));
    }
  
 public void table(ResultSet result) {
        sTB.setModel(DbUtils.resultSetToTableModel(result));
    }
private void loadTableData() {
        // Create an instance of tableLoad and fetch data
        tableLoad tableLoader = new tableLoad();
        ResultSet resultSet = tableLoader.fetchTableData();
        // Call the table method to populate the JTable
        table(resultSet);
    }
//public void executeSQlQuery(String query, String message){
    //Connection con = getConnection();
    //Statement st;
    //try{
        //st = con.createStatement();
        //if(st.executeUpdate(query) == 1)
        //{
            //JOptionPane.showMessageDialog(null, "Data"+message+"Successfully");
        //}else{
            //JOptionPane.showMessageDialog(null, "Data not"+message);
        //}
        
    //}catch(Exception e){
        
    //}
//}
  private void clearFields(){
      idTXT.setText(null);
      nameTXT.setText(null);
      addressTXT.setText(null);
      birthTXT.setText(null);
  }       
    
    
    
    private void Connect() throws SQLException
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn =  DriverManager.getConnection("jdbc:mysql://localhost/studentdatabase","root","");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        idTXT = new javax.swing.JTextField();
        nameTXT = new javax.swing.JTextField();
        birthTXT = new javax.swing.JTextField();
        genderCMB = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        backBtn = new com.k33ptoo.components.KButton();
        addStudentBtn = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sTB = new javax.swing.JTable();
        delstBtn = new com.k33ptoo.components.KButton();
        upstBtn = new com.k33ptoo.components.KButton();
        canBtn = new com.k33ptoo.components.KButton();
        resetBtn = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTXT = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        searchFLD = new javax.swing.JTextField();
        idFLD = new javax.swing.JTextField();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/books.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBackground(new java.awt.Color(255, 0, 204));
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkGradientFocus(750);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 204, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Student ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 5, true));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 160, 50));

        id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        id.setText("ID :");
        kGradientPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 102, 40, -1));

        name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name.setText("Name :");
        kGradientPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 152, -1, -1));

        address.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        address.setText("Address :");
        kGradientPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 204, -1, -1));

        birthday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        birthday.setText("Birthday :");
        kGradientPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 314, -1, -1));

        gender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gender.setText("Gender :");
        kGradientPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));
        kGradientPanel1.add(idTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 99, 180, -1));
        kGradientPanel1.add(nameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 149, 180, -1));

        birthTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthTXTActionPerformed(evt);
            }
        });
        kGradientPanel1.add(birthTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 311, 180, -1));

        genderCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        kGradientPanel1.add(genderCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 311, 153, -1));

        backBtn.setText("Back");
        backBtn.setkBorderRadius(40);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, 110, 30));

        addStudentBtn.setText("Add Student");
        addStudentBtn.setkBorderRadius(40);
        addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(addStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 130, 40));

        sTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Birthday", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        sTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sTB);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 390, 320));

        delstBtn.setText("Delete Student");
        delstBtn.setkBorderRadius(40);
        delstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delstBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(delstBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 130, 40));

        upstBtn.setText("Updated Data");
        upstBtn.setkBorderRadius(40);
        upstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upstBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(upstBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 130, 40));

        canBtn.setText("Cancel");
        canBtn.setkBorderRadius(40);
        canBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(canBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 560, 110, 30));

        resetBtn.setText("Reset");
        resetBtn.setkBorderRadius(40);
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 120, 40));

        addressTXT.setColumns(20);
        addressTXT.setRows(5);
        jScrollPane2.setViewportView(addressTXT);

        kGradientPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 240, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pen.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pencil.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 110, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paper.png"))); // NOI18N
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 110, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/books.png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, 90, 90));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Search Students :");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 120, -1));

        searchFLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFLDActionPerformed(evt);
            }
        });
        searchFLD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFLDKeyReleased(evt);
            }
        });
        kGradientPanel1.add(searchFLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 220, 30));

        idFLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFLDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(idFLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void birthTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthTXTActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void canBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_canBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        clearFields();
        

    }//GEN-LAST:event_resetBtnActionPerformed

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
        
            // TODO add your handling code here:
            String id = idTXT.getText();
            String name = nameTXT.getText();
            String address = addressTXT.getText();
            String birthday = birthTXT.getText();
            String gender = (String)genderCMB.getSelectedItem();
            
            try{
                addControl obj = new addControl();
                obj.studentdetails(id,name,address,birthday,gender);
            }catch(NumberFormatException e){
                
            }
            loadTableData();
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void upstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upstBtnActionPerformed
        // TODO add your handling code here:
                  
                  
    String id = idTXT.getText(); 
    String name = nameTXT.getText();  
    String address = addressTXT.getText();
    String birthday = birthTXT.getText();
    
    try {
            

            updateController controller = new updateController();
            controller.updatee(id, name, address, birthday);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        loadTableData();
    }//GEN-LAST:event_upstBtnActionPerformed

    private void sTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sTBMouseClicked
        // TODO add your handling code here:
        
        int i = sTB.getSelectedRow();
       TableModel model = sTB.getModel();
       idTXT.setText(model.getValueAt(i, 0).toString());
       nameTXT.setText(model.getValueAt(i, 1).toString());
       addressTXT.setText(model.getValueAt(i, 2).toString());
       birthTXT.setText(model.getValueAt(i, 3).toString());
       
    }//GEN-LAST:event_sTBMouseClicked

    private void delstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delstBtnActionPerformed
        // TODO add your handling code here:
        
       String idText = idFLD.getText();
      
       try {
            

            deleteControl controller = new deleteControl();
            controller.delete(idText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        }
       loadTableData();
    }//GEN-LAST:event_delstBtnActionPerformed

    private void searchFLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFLDActionPerformed

    private void searchFLDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFLDKeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_searchFLDKeyReleased

    private void idFLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFLDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton addStudentBtn;
    private javax.swing.JLabel address;
    private javax.swing.JTextArea addressTXT;
    private com.k33ptoo.components.KButton backBtn;
    private javax.swing.JTextField birthTXT;
    private javax.swing.JLabel birthday;
    private com.k33ptoo.components.KButton canBtn;
    private com.k33ptoo.components.KButton delstBtn;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> genderCMB;
    private javax.swing.JLabel id;
    private javax.swing.JTextField idFLD;
    private javax.swing.JTextField idTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField8;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTXT;
    private com.k33ptoo.components.KButton resetBtn;
    private javax.swing.JTable sTB;
    private javax.swing.JTextField searchFLD;
    private com.k33ptoo.components.KButton upstBtn;
    // End of variables declaration//GEN-END:variables
}
