/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.addControll;
import Controller.deleteControlT;
import Controller.updateController;
import Controller.updateControllerT;
import Model.DBConnection;
import static Model.DBConnection.getConnection;
import Model.tableLoadTeach;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tharapathi
 */
public class TeacherView extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form TeacherView
     */
    public TeacherView() {
        initComponents();
        loadTableData();
        
       
        
        try {
            Connect();
        } catch (SQLException ex) {
            Logger.getLogger(TeacherView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    Connection conn;
    PreparedStatement pst;
    //public void tableLoad(){
   
            //try {
               
                //Class.forName("com.mysql.cj.jdbc.Driver");
               
                // Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagementsystem?useSSL=false","root","");
                //Statement stmt = DBConnection.getStatementConnection();
         
                //ResultSet rs = stmt.executeQuery("SELECT * FROM teacher ");
               
            //DefaultTableModel tb1Model = (DefaultTableModel)tTB.getModel();
            //tb1Model.setRowCount(0);
           
            //while(rs.next()){
                //String TId= rs.getString("tid");
                //String name= rs.getString("name");
                //String address= rs.getString("address");
                //String birthday= rs.getString("birthday");
                //String gender= rs.getString("gender");
               
                //String tTB[]= {TId, name, address, birthday, gender};
                //tb1Model.addRow(tTB);
               
            //}
           
        //} catch (Exception e) {
        //}
    //}
    public void search(){
        String srch = searchFLD.getText();
        tableLoadTeach tableLoader = new tableLoadTeach();
        ResultSet resultSet = tableLoader.searchData(srch);
        tableSearch(resultSet);
    }
    
    public void tableSearch(ResultSet result) {
        tTB.setModel(DbUtils.resultSetToTableModel(result));
    }
  
 public void table(ResultSet result) {
        tTB.setModel(DbUtils.resultSetToTableModel(result));
    }
private void loadTableData() {
        // Create an instance of tableLoad and fetch data
        tableLoadTeach tableLoader = new tableLoadTeach();
        ResultSet resultSet = tableLoader.fetchTableData();
        // Call the table method to populate the JTable
        table(resultSet);
    }
    private void clearFields(){
        tidTXT.setText(null);
        tnameTXT.setText(null);
        taddressTXT.setText(null);
        tbirthdayTXT.setText(null);
    }
    
    private void Connect() throws SQLException
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn =  DriverManager.getConnection("jdbc:mysql://localhost/studentdatabase","root","");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TeacherView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void executeSQlQuery(String query , String message){
        Connection con = getConnection();
        Statement st;
        try{
           st = con.createStatement();
           if(st.executeUpdate(query)==1)
           {
              JOptionPane.showMessageDialog(null, "Data"+message+ "Successfully");
           }else{
               JOptionPane.showMessageDialog(null, "Data"+message+"Successfully");
           }
        }catch(SQLException e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        Tid = new javax.swing.JLabel();
        Tname = new javax.swing.JLabel();
        Taddress = new javax.swing.JLabel();
        Tbirthday = new javax.swing.JLabel();
        Tgender = new javax.swing.JLabel();
        tidTXT = new javax.swing.JTextField();
        tnameTXT = new javax.swing.JTextField();
        taddressTXT = new javax.swing.JTextField();
        tbirthdayTXT = new javax.swing.JTextField();
        genderCMb = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTB = new javax.swing.JTable();
        deleteBtn = new com.k33ptoo.components.KButton();
        updateBTN = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchFLD = new javax.swing.JTextField();
        deleteTTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkGradientFocus(750);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 204, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teacher");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 5, true));
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 150, 60));

        Tid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tid.setText("TID :");
        kGradientPanel1.add(Tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 102, 40, -1));

        Tname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tname.setText("Name :");
        kGradientPanel1.add(Tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 152, -1, -1));

        Taddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Taddress.setText("Address :");
        kGradientPanel1.add(Taddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 204, -1, -1));

        Tbirthday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tbirthday.setText("Birthday :");
        kGradientPanel1.add(Tbirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 314, -1, -1));

        Tgender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tgender.setText("Gender :");
        kGradientPanel1.add(Tgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));
        kGradientPanel1.add(tidTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 99, 180, -1));

        tnameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameTXTActionPerformed(evt);
            }
        });
        kGradientPanel1.add(tnameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 149, 180, -1));
        kGradientPanel1.add(taddressTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 180, 74));

        tbirthdayTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbirthdayTXTActionPerformed(evt);
            }
        });
        kGradientPanel1.add(tbirthdayTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 311, 180, -1));

        genderCMb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        kGradientPanel1.add(genderCMb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 311, 153, -1));

        kButton1.setText("Back");
        kButton1.setkBorderRadius(40);
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, 100, 30));

        kButton2.setText("Add Teacher");
        kButton2.setkBorderRadius(40);
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 130, 40));

        tTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TID", "Name", "Address", "Birthday", "Gender"
            }
        ));
        tTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tTB);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 390, 320));

        deleteBtn.setText("Delete Teacher");
        deleteBtn.setkBorderRadius(40);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 130, 40));

        updateBTN.setText("Updated Data");
        updateBTN.setkBorderRadius(40);
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });
        kGradientPanel1.add(updateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 130, 40));

        kButton7.setText("Cancel");
        kButton7.setkBorderRadius(40);
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, 100, 30));

        kButton5.setText("Reset");
        kButton5.setkBorderRadius(40);
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/laptop.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 110, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/markerpen.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 120, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mouse.png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 90, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Search Teachers :");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        searchFLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFLDActionPerformed(evt);
            }
        });
        searchFLD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFLDKeyReleased(evt);
            }
        });
        kGradientPanel1.add(searchFLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 180, -1));
        kGradientPanel1.add(deleteTTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 120, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1120, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbirthdayTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbirthdayTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbirthdayTXTActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
            String tid = tidTXT.getText();
            String name = tnameTXT.getText();
            String address = taddressTXT.getText();
            String birthday = tbirthdayTXT.getText();
            String gender = (String)genderCMb.getSelectedItem();
            
            try{
                
                addControll obj = new addControll();
                obj.studentdetails2(tid,name,address,birthday,gender);
            }catch(NumberFormatException e){
                
            }
            loadTableData();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        // TODO add your handling code here:
    String tid = tidTXT.getText(); 
    String name = tnameTXT.getText();  
    String address = taddressTXT.getText();
    String birthday = tbirthdayTXT.getText();
    
    try {
            

            updateControllerT controller = new updateControllerT();
            controller.updateT(tid, name, address, birthday);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        loadTableData();
        
        
    }//GEN-LAST:event_updateBTNActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String idText = deleteTTXT.getText();
      
       try {
            

            deleteControlT controller = new deleteControlT();
            controller.delete( idText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        }
       loadTableData();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void tTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTBMouseClicked
        // TODO add your handling code here:
        int i = tTB.getSelectedRow();
        TableModel model = tTB.getModel();
        tidTXT.setText(model.getValueAt(i, 0).toString());
        tnameTXT.setText(model.getValueAt(i, 1).toString());
        taddressTXT.setText(model.getValueAt(i, 2).toString());
        tbirthdayTXT.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_tTBMouseClicked

    private void tnameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameTXTActionPerformed

    private void searchFLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFLDActionPerformed

    private void searchFLDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFLDKeyReleased
        // TODO add your handling code here:
        search();
        
    }//GEN-LAST:event_searchFLDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Taddress;
    private javax.swing.JLabel Tbirthday;
    private javax.swing.JLabel Tgender;
    private javax.swing.JLabel Tid;
    private javax.swing.JLabel Tname;
    private com.k33ptoo.components.KButton deleteBtn;
    private javax.swing.JTextField deleteTTXT;
    private javax.swing.JComboBox<String> genderCMb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField searchFLD;
    private javax.swing.JTable tTB;
    private javax.swing.JTextField taddressTXT;
    private javax.swing.JTextField tbirthdayTXT;
    private javax.swing.JTextField tidTXT;
    private javax.swing.JTextField tnameTXT;
    private com.k33ptoo.components.KButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
